apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-lde-pp-ua-tls
spec:
  secretName: k8s-lde-pp-ua
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-lde.pp.ua
  dnsNames:
    - k8s-lde.pp.ua
    - www.k8s-lde.pp.ua
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s-lde.pp.ua
          - www.k8s-lde.pp.ua
